# Generated by Django 5.0.5 on 2024-05-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Protudo',
            new_name='Produto',
        ),
    ]
